export const PHOTOGRAPHER_TYPES = [
  "Portrait",
  "Landscape",
  "Wildlife",
  "Street",
  "Fashion",
  "Event",
  "Sports",
  "Product",
  "Food",
  "Travel",
  "Fine Art",
  "Conceptual",
  "Abstract",
  "Black & White",
  "Silhouette",
  "Macro",
  "Astrophotography",
  "Long Exposure",
  "Aerial/Drone",
  "Architectural",
  "Real Estate",
  "Commercial",
  "Editorial",
  "Documentary",
  "Photojournalism",
  "Lifestyle",
  "Influencer/Instagram",
  "Cinematic",
  "Minimalist",
  "Other"
] as const;

export const CATEGORY_TO_API: Record<string, string> = {
  "Portrait": "PORTRAIT",
  "Landscape": "LANDSCAPE",
  "Wildlife": "WILDLIFE",
  "Street": "STREET",
  "Fashion": "FASHION",
  "Event": "EVENT",
  "Sports": "SPORTS",
  "Product": "PRODUCT",
  "Food": "FOOD",
  "Travel": "TRAVEL",
  "Fine Art": "FINE_ART",
  "Conceptual": "CONCEPTUAL",
  "Abstract": "ABSTRACT",
  "Black & White": "BLACK_AND_WHITE",
  "Silhouette": "SILHOUETTE",
  "Macro": "MACRO",
  "Astrophotography": "ASTROPHOTOGRAPHY",
  "Long Exposure": "LONG_EXPOSURE",
  "Aerial/Drone": "AERIAL_DRONE",
  "Architectural": "ARCHITECTURAL",
  "Real Estate": "REAL_ESTATE",
  "Commercial": "COMMERCIAL",
  "Editorial": "EDITORIAL",
  "Documentary": "DOCUMENTARY",
  "Photojournalism": "PHOTOJOURNALISM",
  "Lifestyle": "LIFESTYLE",
  "Influencer/Instagram": "INFLUENCER_INSTAGRAM",
  "Cinematic": "CINEMATIC",
  "Minimalist": "MINIMALIST",
  "Other": "OTHER"
};
